/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lst_burns_mesureboottime_DeviceHelper */

#ifndef _Included_com_lst_burns_mesureboottime_DeviceHelper
#define _Included_com_lst_burns_mesureboottime_DeviceHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lst_burns_mesureboottime_DeviceHelper
 * Method:    native_getBootTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_lst_burns_mesureboottime_DeviceHelper_native_1getBootTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
